### ISSUE TITLE
"Quiet mode" has misleading description

### ISSUE THREAD

**Issue by TJC** [lukealford/abb-speedtest-cli#12]
The `--quiet` mode is described as: 
```
.option('-q, --quiet [optional]', 'disables result reporting to ABB')
```

However the actual effect in the code seems to be mixed -- it also reduces the verbosity of console log output (see #11 )

Could I suggest using two flags, perhaps?
Maybe `--quiet` to reduce the console status output down to just the data, and `--no-report` to disable the reporting back to ABB?

cc @ChrisRiddell @borhub

**Comment by ChrisRiddell** [comment]
I’ll discuss this with @lukealford and see what he thinks I’m happy to split them up like that and put in another pull request.

**Comment by lukealford** [comment]
@ChrisRiddell feel free to do that, don't forget to update the readme  ;)

**Comment by lukealford** [comment]
new option for this is `--hide` @TJC
