### ISSUE TITLE
JSON output is... not JSON

### ISSUE THREAD

**Issue by TJC** [lukealford/abb-speedtest-cli#8]
Running the program with `--json` produces output that is similar to JSON, but is not valid JSON, and not parsed by JSON libraries.
For example:
```
results: {
  location: 'Melbourne',
  ping: '8',
  jitter: '2',
  download: '108.4',
  upload: '21.4',
  date: '8/30/2020 12:26:30 pm'
}
```
That won't parse in either the command-line `jq` utility, nor Ruby or Scala's JSON parsers...

Can I suggest aiming for a format more like this?
```
{ "location": "Melbourne", "ping": 8, "jitter": 2, "download": 108.4, "upload": 21.4, "date": "2020-08-30T00:26:30" }
```

That will enable the output to be parsed by common JSON libraries, or imported into databases and spreadsheets easily.

**Comment by TJC** [comment]
I think this just needs line 115 to change to read:
```
console.log(JSON.stringify(result.result));
```

**Comment by TJC** [comment]
(Although that won't fix the date from being in US MM/DD/YYY format)

**Comment by risb0r** [comment]
Possible to include a "Host" line item to allow for importing and sorting into a time series db such as influxdb for displaying in Grafana?

**Comment by lukealford** [comment]
@TJC  This is only the console log output, not the actual output / saved file are you parsing the console log?
I know for a fact the json save is valid and works as it should, I've been using it for quite some time. 

@risb0r I'll add hostname to the default output.

**Comment by TJC** [comment]
> This is only the console log output, not the actual output / saved file are you parsing the console log?

I'm running the app with just the `--json` parameter. I expected that to result in JSON output. It seemed like a reasonable expectation :)
It was a bit weird that it mutated the console output away from the default print-out, but not to an actual JSON format.

**Comment by TJC** [comment]
Thanks for merging the change in quickly.
